version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: taskboard
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: taskboard
      DB_USER: admin
      DB_PASSWORD: secret123
      JWT_SECRET: dev-secret
    ports:
      - "3001:3001"

  task-service:
    build: ./task-service
    container_name: task-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: taskboard
      DB_USER: admin
      DB_PASSWORD: secret123
      JWT_SECRET: dev-secret
    ports:
      - "3002:3002"

  log-service:
    build: ./log-service
    container_name: log-service
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: taskboard
      DB_USER: admin
      DB_PASSWORD: secret123
    ports:
      - "3003:3003"

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - frontend
      - auth-service
      - task-service
      - log-service
    ports:
      - "8888:80"
      - "4443:443"

volumes:
  postgres_data:
